name: Check Maintained Package Builds

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  check-builds:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Clone nixpkgs
        run: |
          git clone --depth 1 \
            --branch master \
            https://github.com/NixOS/nixpkgs.git \
            ./nixpkgs-latest
      - name: Run Checks
        run: |
          nix develop \
            --ignore-env \
            --keep MAINTAINER_HANDLE \
            --keep NIXPKGS_SRC_PATH \
            --keep GH_TOKEN \
            --command bash run_checks.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAINTAINER_HANDLE: ${{ secrets.MAINTAINER_HANDLE }}
          NIXPKGS_SRC_PATH: ./nixpkgs-latest
